---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000


---
# Reference: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gateway-server:0.0.1
          # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
          # https://kubernetes.io/docs/concepts/containers/images/#updating-images
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
