---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---
# Reference: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registryservice-deployment
spec:
  selector:
    matchLabels:
      app: registry-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-service
          image: registry-service:0.0.1
          # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
          # https://kubernetes.io/docs/concepts/containers/images/#updating-images
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
