openapi: 3.0.3
info:
  title: Dodgy Drivers Online mall - OpenAPI 3.0
  description: |-
    This is an online shopping mall Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  version: 0.0.1
servers:
  - url: http://localhost:9003/api
  - url: https://dodgycoders.ucd.ie/api
tags:
  - name: payment
    description: Payments status of the orders
paths:
  /payment/{paymentId}:
    get:
      tags:
        - payment
      summary: Get all the payments
      operationId: getAllPayment
      parameters:
        - name: paymentId
          in: path
          description: ID of the payment
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successfully get all payments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "400":
          description: Invalid ID
        "404":
          description: Payments not found
  /payment:
    post:
      tags:
        - payment
      summary: add new payment
      operationId: addPayment
      responses:
        "405":
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Payment"
components:
  schemas:
    Payment:
      type: object
      required:
        - userId
        - paymentStatus
        - paymentPalcedTime
        - amount
      properties:
        userId:
          type: integer
          format: int64
          example: 1
        amount:
          type: integer
          example: 66
        paymentPlacedTime:
          type: date-time
          example: "2022-11-11T15:30:45Z"
        paymentStatus:
          type: string
          description: payment status
          example: pendding
          enum:
            - pendding
            - completed
            - cancled
