---
apiVersion: v1
kind: Service
metadata:
  name: goods-service

spec:
  selector:
    app: goods-service

  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002

---
# Reference: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodsservice-deployment
spec:
  selector:
    matchLabels:
      app: goods-service

  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: goods-service

    spec:
      containers:
        - name: goods-service
          image: goods-service:0.0.1
          # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
          # https://kubernetes.io/docs/concepts/containers/images/#updating-images
          imagePullPolicy: Never
          ports:
            - containerPort: 9002